# 11.异常处理

当检测到一个错误时，解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的"异常"。如在进行文件操作时，如果`open`函数指定的文件并不存在或者无法打开，那么将引发异常状况导致程序崩溃。为了让代码有一定的健壮性和容错性，我们可以使用Python的异常机制对可能在运行时发生状况的代码进行适当的处理。

```python
f = open('致橡树.txt', 'r', encoding='utf-8')
print(f.read())
f.close()
```

进行如下修改：

```python
def main():
    f = None
    try:
        f = open('致橡树.txt', 'r', encoding='utf-8')
        print(f.read())
    except FileNotFoundError:
        print('无法打开指定的文件!')
    except LookupError:
        print('指定了未知的编码!')
    except UnicodeDecodeError:
        print('读取文件时解码错误!')
    finally:
        if f:
            f.close()

if __name__ == '__main__':
    main()
```

### 1.异常的作用

#### （1）错误处理

每当在运行时检测到程序错误时，Python 就会引发异常。可以在程序代码中捕捉和处理错误或者忽略已发生的异常。如果忽略错误，Python 默认的异常处理行为将启动停止程序并打印出错消息。如果不想启动这种默认行为，就要编写 try语句来捕获异常并从中恢复。

#### （2）事件通知

异常也可用于发出有效状态的信号，而无需在程序中四处传递结果标签，或是刻意对其进行测试。

#### （3）特殊情况处理

有时发生了某种极为罕见的情况，很难证明调整代码在多个场合处理它是合理的。这是可以通过在程序更高层面的异常处理器来处理这些异常情况，这时可以省略编写处理应对特殊情况的代码。

#### （4）终止行为

无论程序中是否发生异常，try/finally 语句可确保实行需要的结束操作。较新的with语句在这一方面为支持它的对象提供了一种替代方案。

#### （5）非常规控制流程

因为异常是一种高级的和结构化的“go to”语句，所以可以将它作为实现奇异控制流程的基础。例如，虽然反向跟踪 (backtracking)并不是语言本身的一部分，但是在 Python 中你可以使用异常外加一些辅助逻辑来充当“go to”语句，例如，raise语句可用来跳出多重循环。

### 2.Python 的异常机制

Python中和异常相关的关键字有六个，分别是`try`、`except`、`assert`、`else`、`finally`和`raise`。

```python
try:
    #业务实现代码
except SubException as e:
    # 异常处理块1
    ...
except SubException2 as e:
    # 异常处理块2
    ...
except (NameError, ZeroDivisionError):
    # 捕获多个异常：异常处理块3
    ...
except Exception:
	# 捕获所有异常：异常处理块4
    ...
else:
    #正常处理块
finally :
    #资源回收块
    ...
```

在Python中，我们可以将运行时会出现状况的代码放在`try`代码块中，在`try`后面可以跟上一个或多个`except`块来捕获异常并进行相应的处理。所以我们在`try`后面跟上了三个`except`分别处理这三种不同的异常状况。在`except`后面，我们还可以加上`else`代码块，这是`try` 中的代码没有出现异常时会执行的代码，而且**`else`中的代码不会再进行异常捕获，也就是说如果遇到异常状况，程序会因异常而终止并报告异常信息。**最后我们使用`finally`代码块来关闭打开的文件，释放掉程序中获取的外部资源。由于`finally`块的代码不论程序正常还是异常都会执行，甚至是调用了`sys`模块的`exit`函数终止Python程序，`finally`块中的代码仍然会被执行（因为`exit`函数的本质是引发了`SystemExit`异常），因此我们把`finally`代码块称为“总是执行代码块”，它最适合用来做释放外部资源的操作。

| 分句形式                      | 说明                                                   |
| ----------------------------- | ------------------------------------------------------ |
| `except:`                     | 捕捉所有 (其他)异常类型。                              |
| `except name:`                | 只捕捉指定的异常。                                     |
| `except name as e:`           | 捕捉所列的异常并将该异常实例赋值给名称e。              |
| `except (name1, name2) `      | 捕捉任何列出的异常。                                   |
| `except (name1, name2) as e:` | 捕捉任何列出的异常，并将异常实例元组赋值给名称 value。 |
| `else`                        | 如果没有引发异常，就会运行。                           |
| `finally`                     | 总是在退出 try 语句时运行此代码块。                    |

### 3.几种异常机制的应用

#### （1）try-finally语句

如果想保证程序在执行后无论程序的异常行为如何都有动作一定发生，那么就可以采用try/finally形式。

在实际应用中，一方面可以用于定义一定会发生的清理动作例如必要的文件关闭以及服务器断开连接等，另一方面，在嵌套异常机制中，使用finally语句构建异常链。

#### （2）raise实现异常传递

```python
try:
   raise IndexError('spam')
except IndexError:
    print('propagating)
    raise
```

这样执行 raise时，就能重新引发异常，并将其传递给更高层的处理程序 (或者顶层的默认处理程序，它会停止程序并打印标准出错消息)。

#### （3）assert异常调试

assert语句用于异常调试，是raise常见使用模式的一种语法简写，assert 可视为条件式的raise 语句。

```python
assert test,data

if __debug__:
    if not test:
        raise AssertionError(data)
```

如果 test计算结果为假，那么`Python` 就会引发异常，`data`项(如果提供了的话)将作为异常构造函数的参数。跟所有异常一样，引发的`AssertionError` 异常如果没被 `try`捕捉，就会终止程序，在此情况下` data `项将显示为标准出错消息的一部分。

assert 语句通常是在开发期间用于验证程序状况的。当它显示时，其出错消息正文会自动包括源代码的行信息，以及列在assert 语句中的值。

```python
def f(x):
    assert x<0，'x must be negativereturn X**2
```

assert 几乎都是用来捕获用户定义的约束条件，而不是捕捉实际的程序设计错误。因为Python 会自行捕获程序的设计错误，所以通常没必要写assert 去捕捉超出索引值、类型不匹配以及除数为零之类的事情。

### 4.内置异常与自定义异常

Python中内置了大量的异常类型，除了上面代码中用到的异常类型以及之前的课程中遇到过的异常类型外，还有许多的异常类型，其继承结构如下所示。

```python
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
```

从上面的继承结构可以看出，Python中所有的异常都是`BaseException`的子类型，它有四个直接的子类，分别是：`SystemExit`、`KeyboardInterrupt`、`GeneratorExit`和`Exception`。其中，`SystemExit`表示解释器请求退出，`KeyboardInterrupt`是用户中断程序执行（按下`Ctrl+c`），`GeneratorExit`表示生成器发生异常通知退出。`Exception`类，它是常规异常类型的父类型，很多的异常都是直接或间接的继承自`Exception`类。如果Python内置的异常类型不能满足应用程序的需要，我们可以自定义异常类型，而自定义的异常类型也应该直接或间接继承自`Exception`类，当然还可以根据需要重写或添加方法。

```python
# 自定义异常类，继承Exception
class ShortInputError(Exception):
    def __init__(self, length, min_len):
        self.length = length
        self.min_len = min_len

    # 设置抛出异常的描述信息
    def __str__(self):
        return f'你输入的长度是{self.length}, 不能少于{self.min_len}个字符'


def main():
    try:
        con = input('请输入密码：')
        if len(con) < 3:
            raise ShortInputError(len(con), 3)
    except Exception as result:
        print(result)
    else:
        print('密码已经输入完成')


main()
```

在Python中，抛出自定义异常的语法为` raise 异常类对象`。

### 5.常用的异常设计模式









### 6.Python 异常使用规范

- 不要过度使用异常
  - 把异常和普通错误混淆在一起，不再编写任何错误处理代码，而是以引发异常来代替错误处理。
  - 使用异常处理来代替流程控制。
- **不要使用过于庞大的 try 块**
  - 在 try 块里放置大量的代码，然后紧跟大量的 except 块，增加了编程复杂度。
- **不要忽略捕获到的异常**
  - 处理异常。对异常进行合适的修复，然后绕过异常发生的地方继续运行；或者用别的数据进行计算，以代替期望的方法返回值；或者提示用户重新操作……总之，程序应该尽量修复异常，使程序能恢复运行。
  - 重新引发新异常。把在当前运行环境下能做的事情尽量做完，然后进行异常转译，把异常包装成当前层的异常，重新传给上层调用者。
  - 在合适的层处理异常。如果当前层不清楚如何处理异常，就不要在当前层使用 except 语句来捕获该异常，让上层调用者来负责处理该异常。









